import os

filepath = r"c:\Users\ARCHIVE STUDIO\Downloads\stitch_process\index.html"

with open(filepath, "r", encoding="utf-8") as f:
    html = f.read()

replacements = {
    'lang="en"': 'lang="ru"',
    "<title>InnoHome Architecture</title>": "<title>Архитектура InnoHome</title>",
    ">Home<": ">Главная<",
    ">Services<": ">Услуги<",
    ">Portfolio<": ">Портфолио<",
    ">Contact<": ">Контакты<",
    ">Get Started<": ">Начать<",
    "Architectural Laboratory": "Архитектурная лаборатория",
    ">Explore Houses<": ">Смотреть дома<",
    ">Our Process<": ">Наш процесс<",
    "Scroll to discover": "Листайте вниз",
    "Specialized Expertise": "Специализированная экспертиза",
    ">Automation<": ">Автоматизация<",
    "Intelligent home ecosystems that learn and adapt. We implement seamless automation for lighting, acoustics, and environment control, ensuring your space responds intuitively to your presence.": "Интеллектуальные домашние экосистемы, которые обучаются и адаптируются. Мы внедряем бесшовную автоматизацию освещения, акустики и климат-контроля, чтобы ваше пространство интуитивно реагировало на ваше присутствие.",
    ">Energy Infrastructure<": ">Энергетическая инфраструктура<",
    "Resilient power supply solutions tailored for high-end residential needs. From smart grid integration to backup energy storage, we ensure uninterrupted performance and efficiency.": "Надежные решения для электроснабжения, разработанные для элитных жилых объектов. От интеграции умных сетей до резервного хранения энергии — мы обеспечиваем бесперебойную работу и эффективность.",
    ">Security Systems": ">Системы безопасности",
    "Sophisticated low-current networks and high-definition video surveillance. We design discreet security layers that provide total peace of mind without compromising the aesthetic integrity of the home.": "Сложные слаботочные сети и видеонаблюдение высокой четкости. Мы создаем скрытые системы безопасности, которые обеспечивают полное спокойствие, не нарушая эстетическую целостность дома.",
    "Index / Selected Works": "Индекс / Избранные работы",
    "View All Projects": "Смотреть все проекты",
    "The Monolith": "Монолит",
    "Switzerland": "Швейцария",
    "Nexus Hub": "Нексус Хаб",
    "Germany": "Германия",
    "Precision Engineering": "Точная инженерия",
    "ARCHITECTURAL <br />INTELLIGENCE.": "АРХИТЕКТУРНЫЙ <br />ИНТЕЛЛЕКТ.",
    "Experience the synergy of architectural depth and advanced home intelligence. We redefine luxury through invisible technology and effortless control.": "Почувствуйте синергию архитектурной глубины и передового домашнего интеллекта. Мы переосмысливаем роскошь с помощью невидимых технологий и легкого управления.",
    "Our Core Capabilities": "Наши ключевые возможности",
    "Home Automation": "Домашняя автоматизация",
    "Comprehensive smart home orchestration that disappears into your architecture. We create intuitive environments that respond to your presence with surgical precision.": "Комплексная оркестровка умного дома, которая растворяется в вашей архитектуре. Мы создаем интуитивно понятную среду, реагирующую на ваше присутствие с хирургической точностью.",
    "Precision Heating": "Точное отопление",
    "Advanced thermal engineering for the modern residence. Multi-zone climate control systems designed for invisible installation and absolute efficiency.": "Передовая теплотехника для современных резиденций. Многозонные системы климат-контроля, созданные для скрытого монтажа и абсолютной эффективности.",
    "Integrated Power": "Интегрированное питание",
    "Uninterruptible power solutions and energy management. We engineer robust electrical backbones that support the most demanding smart home ecosystems.": "Решения для бесперебойного питания и управления энергией. Мы проектируем надежные электрические магистрали для самых требовательных экосистем умного дома.",
    "Network &amp; Security": "Сети и безопасность",
    "High-speed low-current networking and AI-powered video surveillance. Enterprise-grade connectivity paired with sophisticated perimeter protection.": "Высокоскоростные слаботочные сети и видеонаблюдение на базе ИИ. Подключение корпоративного уровня в сочетании с передовой защиты периметра.",
    "LEARN MORE": "УЗНАТЬ БОЛЬШЕ",
    "Project <br />Archives": "Архивы <br />проектов",
    "A curated selection of cinematic architectural visions. Exploring the boundaries between digital art and structural reality.": "Тщательно отобранная коллекция кинематографичных архитектурных видений. Исследование границ между цифровым искусством и структурной реальностью.",
    "All Concepts": "Все концепты",
    "Residential": "Жилые",
    "Brutalist": "Брутализм",
    "Minimalism": "Минимализм",
    "Pavilions": "Павильоны",
    "The Obsidian Villa": "Обсидиановая вилла",
    "Reykjavik, Iceland": "Рейкьявик, Исландия",
    "Monolith Retreat": "Монолитное убежище",
    "Atacama, Chile": "Атакама, Чили",
    "Ethereal Lofts": "Эфирные лофты",
    "Berlin, Germany": "Берлин, Германия",
    "Berlin,\n                                    Germany": "Берлин,\n                                    Германия",
    "Void Pavilion": "Павильон Пустоты",
    "Kyoto, Japan": "Киото, Япония",
    "Kyoto,\n                                    Japan": "Киото,\n                                    Япония",
    "Alpine Node": "Альпийский узел",
    "Zermatt, Switzerland": "Церматт, Швейцария",
    "Lumina Gallery": "Галерея Люмина",
    "Copenhagen, Denmark": "Копенгаген, Дания",
    ">Explore<": ">Смотреть<",
    "Limited Edition": "Лимитированная серия",
    "Zenith\n                                    <br />Heights": "Зенитные\n                                    <br />высоты",
    "A study in verticality and shadow. High-end residential concept focusing on negative space and natural light filtration through structural voids.": "Исследование вертикальности и тени. Элитный жилой концепт с акцентом на негативное пространство и фильтрацию естественного света через структурные пустоты.",
    "View Full Case Study": "Смотреть полный кейс",
    "Previous": "Назад",
    "Next ": "Вперед ",
    "Design Consultation": "Дизайн-консультация",
    "Build Your <br />Legacy.": "Создайте свое <br />наследие.",
    "Transforming spaces into intelligent environments. Let's start the conversation about your next architectural masterpiece.": "Превращение пространств в интеллектуальную среду. Давайте начнем разговор о вашем следующем архитектурном шедевре.",
    "The Form": "Форма",
    "Submit your project details for a private assessment.": "Оставьте данные вашего проекта для индивидуальной оценки.",
    "Full Name": "Полное имя",
    'placeholder="John Doe"': 'placeholder="Иван Иванов"',
    "Email Address": "Email адрес",
    "Inquiry Type": "Тип запроса",
    "Residential Automation": "Автоматизация жилья",
    "Commercial Solutions": "Коммерческие решения",
    "System Integration": "Интеграция систем",
    "Technical Support": "Техническая поддержка",
    "The Vision": "Видение",
    "Tell us about your space...": "Расскажите нам о вашем пространстве...",
    "Initialize Project": "Начать проект",
    "Initialize\n                                        Project": "Начать\n                                        проект",
    "Global Headquarters": "Штаб-квартира",
    "Explore Location": "Исследовать локацию",
    "Communication": "Связь",
    "Inquiries": "Запросы",
    "Crafting cinematic living spaces since 2014.": "Создаем кинематографичные жилые пространства с 2014 года.",
    ">Studio<": ">Студия<",
    "Our Ethos": "Наши принципы",
    "Laboratory": "Лаборатория",
    "Sustainability": "Экологичность",
    "Awards": "Награды",
    ">Connect<": ">Связь<",
    ">Newsletter<": ">Рассылка<",
    'placeholder="YOUR EMAIL"': 'placeholder="ВАШ EMAIL"',
    "© 2024 INNOHOME Lab. All rights reserved.": "© 2024 INNOHOME Lab. Все права защищены.",
    "Privacy Policy": "Политика конфиденциальности",
    "Terms of Service": "Условия использования"
}

for k, v in replacements.items():
    html = html.replace(k, v)

# Fix some multiline / formatting specific ones manually

html = html.replace('Zenith\n                                    <br />Heights', 'Зенитные <br />высоты')
html = html.replace('Berlin,\n                                    Germany', 'Берлин, Германия')
html = html.replace('Kyoto,\n                                    Japan', 'Киото, Япония')

with open(filepath, "w", encoding="utf-8") as f:
    f.write(html)
